name: netalign

channels:
  - pytorch 
  - conda-forge
  - defaults
  
dependencies:
  - pip
  - python
  - pytorch
  - biopython  
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - networkx
  - seaborn
  - setuptools
  - tqdm