networkfolder: "data/intact"
species: 
    - "fly"
    - "mouse"
    - "rat" 
    - "bakers"
beta: 0.01
gamma: 0.25
r_iter: 10
isorank_alpha: 0.6
output_cluster: "data/clusters/R-intact-cluster-0.6.pkl"